---
abstract: 'USB Device Descriptor'
author:
  - 'Brandon Fosdick <bfoz@bfoz.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: USB-Descriptor-Device
provides:
  USB::Descriptor:
    file: lib/USB/Descriptor.pm
    version: 2
  USB::Descriptor::Configuration:
    file: lib/USB/Descriptor/Configuration.pm
    version: 1
  USB::Descriptor::Device:
    file: lib/USB/Descriptor/Device.pm
    version: 1
  USB::Descriptor::Endpoint:
    file: lib/USB/Descriptor/Endpoint.pm
    version: 1
  USB::Descriptor::Interface:
    file: lib/USB/Descriptor/Interface.pm
    version: 1
  USB::HID:
    file: lib/USB/HID.pm
    version: 1
  USB::HID::Descriptor::Class:
    file: lib/USB/HID/Descriptor/Class.pm
    version: 1
  USB::HID::Descriptor::Interface:
    file: lib/USB/HID/Descriptor/Interface.pm
    version: 1
  USB::HID::Descriptor::Report:
    file: lib/USB/HID/Descriptor/Report.pm
    version: 1
  USB::HID::Report:
    file: lib/USB/HID/Report.pm
    version: 1
  USB::HID::Report::Field:
    file: lib/USB/HID/Report/Field.pm
    version: 1
requires:
  perl: 5.01
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 3
